sudo: required
services:
  - docker
before_install:
  - docker build -t vbrar/docker-react -f Dockerfile.dev .
script:
  - docker run vbrar/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-us-west-2-783682514511
  bucket_path: docker
  on:
    branch: master